name: tdlib_generator

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  json_annotation: 4.9.0
  code_builder: 4.5.0
  dart_style: 3.1.1
  pool: ^1.5.1

dev_dependencies:
  build_runner: 2.6.0
  json_serializable: 6.10.0
